Repository fga-eps-mds/2020.1-stay-safe-front-end, pull requests merged in 2020-11, with the labels that each got.

#64 Implement loads
  package-lock.json
  package.json
  src/components/CircularLoader/index.tsx
  src/components/CircularLoader/styles.ts
  src/components/HeatMap/index.tsx
  src/components/Loader/index.tsx
  src/components/Loader/styles.ts
  src/hooks/user.tsx
  src/routes.tsx
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/Home/index.tsx
  src/screens/Login/index.tsx
  src/screens/NeighborhoodReview/impressions.ts
  src/screens/NeighborhoodReview/index.tsx
  src/screens/Occurrence/index.tsx
  src/screens/Occurrences/index.tsx
  src/screens/Review/index.tsx
  src/screens/Settings/index.tsx
  src/services/neighborhood.ts
  src/services/neighborhood.tsx
  src/services/occurrences.ts
  src/services/occurrencesSecretary.ts
  src/services/users.ts
  yarn.lock
Labels: feature

#68 Favorite places
  package-lock.json
  package.json
  src/routes.tsx
  src/screens/FavoritePlaces/index.tsx
  src/screens/FavoritePlaces/styles.ts
  src/screens/Home/index.tsx
  src/screens/Profile/buttonsObject.ts
  src/screens/Profile/index.tsx
  src/services/favoritePlaces.ts
Labels: feature

#66 Add the coordinates of SP on front and use on heatmap
  src/components/HeatMap/coordinates.ts
  src/components/HeatMap/coordinates/coordinatesDF.ts
  src/components/HeatMap/index.tsx
Labels: feature

#72 Add information about features
  src/components/HeatMap/index.tsx
  src/components/InfoModal.tsx
  src/screens/Home/index.tsx
  src/screens/Home/searchOptions.ts
  src/screens/Home/styles.ts
  src/screens/NeighborhoodReview/index.tsx
  src/screens/NeighborhoodReview/styles.ts
Labels: feature

#81 Improve neighborhood review flow
  package-lock.json
  package.json
  src/components/InfoModal.tsx
  src/components/NeighborhoodImpressions/impressions.ts
  src/components/NeighborhoodImpressions/index.tsx
  src/components/NeighborhoodImpressions/styles.ts
  src/components/NeighborhoodInfo/index.tsx
  src/interfaces/neighborhood.ts
  src/interfaces/occurrence.ts
  src/routes.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/NeighborhoodReview/index.tsx
  src/screens/NeighborhoodReview/styles.ts
  src/screens/Neighborhoods/index.tsx
  src/screens/Neighborhoods/styles.ts
  src/screens/Review/index.tsx
  src/screens/Review/styles.ts
Labels: enhancement

#85 Implement search screen
  src/components/Dropdown.tsx
  src/interfaces/neighborhood.ts
  src/screens/Home/searchOptions.ts
  src/screens/Home/styles.ts
  src/screens/Occurrence/dropdownConstants.ts
  src/screens/Occurrence/index.tsx
  src/screens/Occurrence/styles.ts
  src/screens/Search/index.tsx
  src/screens/Search/styles.ts
Labels: feature

#87 Standardize buttons and error messages
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/NormalForms.tsx
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/CityStatistics/styles.ts
  src/screens/FavoritePlaces/index.tsx
  src/screens/FavoritePlaces/styles.ts
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Home/tabs.ts
  src/screens/Login/index.tsx
  src/screens/NeighborhoodReview/index.tsx
  src/screens/NeighborhoodReview/styles.ts
  src/screens/Neighborhoods/index.tsx
  src/screens/Neighborhoods/styles.ts
  src/screens/Occurrence/index.tsx
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Rating/index.tsx
  src/screens/Search/index.tsx
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
  src/utils/dates.ts
  src/utils/scalling.ts
  src/utils/validateField.ts
  src/utils/validateOccurrence.ts
  src/utils/validateUser.ts
Labels: enhancement

#86 Break map and filter modals in two
  src/components/FloatingButton/index.tsx
  src/components/FloatingButton/styles.ts
  src/components/HeatMap/index.tsx
  src/components/StayMarker/index.tsx
  src/screens/Cadastro/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Login/index.tsx
Labels: enhancement, feature

#97 Map and User hook improvements
  src/components/HeatMap/index.tsx
  src/components/Loader/styles.ts
  src/components/SelectPointOnMap/index.tsx
  src/components/SelectPointOnMap/styles.ts
  src/components/StayNormalMap.tsx
  src/hooks/user.tsx
  src/screens/FavoritePlaces/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Occurrence/index.tsx
  src/screens/Report/index.tsx
Labels: enhancement

#101 Change Search Screen
  src/components/Cards.tsx
  src/components/NormalForms.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/Search/index.tsx
  src/screens/Search/styles.ts
Labels: enhancement

#102 Enhancement Login Modal
  src/components/ErrorModal.tsx
  src/components/LoggedInModal.tsx
  src/hooks/user.tsx
  src/navigation/HomeTabBar.tsx
  src/routes.tsx
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/FavoritePlaces/index.tsx
  src/screens/Home/index.tsx
  src/screens/Login/index.tsx
  src/screens/Occurrence/index.tsx
  src/screens/Profile/index.tsx
  src/screens/Rating/index.tsx
  src/screens/Report/index.tsx
Labels: enhancement
