Repository fga-eps-mds/2020.1-stay-safe-front-end, pull requests merged in 2020-12, with the labels that each got.

#105 Create floating button
  src/hooks/user.tsx
  src/navigation/HomeTabBar.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
Labels: enhancement, feature

#108 Suggest Nearby Precinct
  src/screens/Occurrence/index.tsx
Labels: feature

#110 List cities by crime
  src/components/StatisticsCard/index.tsx
  src/components/StatisticsCard/styles.ts
  src/interfaces/statistics.ts
  src/routes.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/CrimeStatistics/crimesConstants.ts
  src/screens/CrimeStatistics/index.tsx
Labels: feature

#111 App Tutorial Screen
  package-lock.json
  package.json
  src/hooks/user.tsx
  src/img/tutorial/1.png
  src/img/tutorial/10.png
  src/img/tutorial/11.png
  src/img/tutorial/12.png
  src/img/tutorial/13.png
  src/img/tutorial/14.png
  src/img/tutorial/15.png
  src/img/tutorial/16.png
  src/img/tutorial/17.png
  src/img/tutorial/18.png
  src/img/tutorial/19.png
  src/img/tutorial/2.png
  src/img/tutorial/20.png
  src/img/tutorial/3.png
  src/img/tutorial/4.png
  src/img/tutorial/5.png
  src/img/tutorial/6.png
  src/img/tutorial/7.png
  src/img/tutorial/8.png
  src/img/tutorial/9.png
  src/routes.tsx
  src/screens/Tutorial/index.tsx
  src/screens/Tutorial/slidesScreens.ts
  src/screens/Tutorial/styles.ts
  yarn.lock
Labels: feature

#109 Fix the bug when has some error to connect to server
  src/components/HeatMap/index.tsx
  src/hooks/user.tsx
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/Home/index.tsx
  src/screens/Login/index.tsx
  src/screens/Neighborhoods/index.tsx
  src/screens/Occurrence/index.tsx
  src/screens/Occurrences/index.tsx
  src/screens/Rating/index.tsx
  src/screens/Rating/styles.ts
  src/screens/Settings/index.tsx
Labels: bug

#121 Notification Switch
  src/screens/Settings/buttonsObject.ts
  src/screens/Settings/index.tsx
Labels: enhancement

#115 Resolve bug on open keyboard
  src/navigation/HomeTabBar.tsx
  src/screens/Report/index.tsx
Labels: bug

#120 Notification redirect
  app.json
  src/hooks/user.tsx
  src/navigation/HomeTabBar.tsx
  src/routes.tsx
  src/screens/Occurrence/index.tsx
  src/screens/Tutorial/index.tsx
  src/screens/Tutorial/slidesScreens.ts
  src/screens/Tutorial/styles.ts
  src/services/notifications.ts
  src/services/occurrences.ts
Labels: enhancement

#125 Map Fixes
  src/components/HeatMap/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
Labels: bug

#124 Add About Screen
  assets/splash.png
  src/fonts/Age.otf
  src/hooks/user.tsx
  src/routes.tsx
  src/screens/About/index.tsx
  src/screens/About/styles.ts
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/NeighborhoodReview/index.tsx
  src/screens/Rating/index.tsx
  src/screens/Settings/buttonsObject.ts
  src/screens/Settings/index.tsx
  src/screens/Tutorial/index.tsx
  src/screens/Tutorial/styles.ts
  yarn-error.log
Labels: enhancement, feature
