Repository fga-eps-mds/2020.1-stay-safe-front-end, pull requests merged in 2020-10, with the labels that each got.

#27 Associate ccurrence with a location
  src/components/StayAlert/index.tsx
  src/components/StayAlert/styles.ts
  src/routes.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Occurrence/dropdownConstants.ts
  src/screens/Occurrence/index.tsx
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
  src/services/occurrences.tsx
Labels: feature

#29 Create the Occurrence Screen
  package-lock.json
  package.json
  src/navigation/HomeTabBar.tsx
  src/routes.tsx
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
  src/screens/Occurrence/index.tsx
  src/screens/Occurrences/index.js
  src/screens/Occurrences/styles.js
  src/screens/Settings/index.tsx
  src/services/occurrences.tsx
  src/utils/dates.js
  src/utils/validateOccurrence.tsx
Labels: feature

#36 Update existing screens according to the prototype
  src/components/HeaderTitle/index.tsx
  src/components/NormalForms.tsx
  src/screens/Cadastro/index.tsx
  src/screens/Login/index.tsx
  src/screens/Occurrence/index.tsx
  src/screens/Occurrence/styles.ts
  src/screens/Occurrences/index.js
  src/screens/Occurrences/styles.js
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Settings/buttonsObject.ts
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
Labels: enhancement

#35 Creating Occurrence Details screen
  src/routes.tsx
  src/screens/Home/index.tsx
  src/screens/OccurrenceDetails/index.tsx
  src/screens/OccurrenceDetails/styles.ts
Labels: enhancement, feature

#41 Show the correct value when editing occurrence
  src/navigation/HomeTabBar.tsx
  src/screens/Occurrence/index.tsx
Labels: bug

#37 Standardizing code
  src/components/LoggedInModal.tsx
  src/navigation/HomeTabBar.tsx
  src/routes.tsx
  src/screens/Cadastro/index.tsx
  src/screens/HeatMap/index.tsx
  src/screens/Home/index.tsx
  src/screens/Login/index.tsx
  src/screens/Occurrence/index.tsx
  src/screens/OccurrenceDetails/index.tsx
  src/screens/Occurrences/index.tsx
  src/screens/Occurrences/styles.ts
  src/screens/Profile/index.tsx
  src/screens/Report/index.tsx
  src/screens/Search/index.tsx
  src/screens/Settings/index.tsx
  src/services/occurrences.tsx
  src/services/occurrencesSecretary.tsx
  src/services/users.tsx
  src/utils/dates.js
  src/utils/dates.tsx
  src/utils/scalling.tsx
  src/utils/validateOccurrence.tsx
  src/utils/validateUpdateUser.tsx
  src/utils/validateUser.tsx
Labels: enhancement

#40 Delete occurrence correctly
  src/components/HeaderTitle/styles.ts
  src/screens/Home/index.tsx
  src/screens/Occurrences/index.tsx
  src/screens/Occurrences/styles.ts
  src/screens/Profile/index.tsx
  src/screens/Settings/index.tsx
Labels: bug

#45 View crimes statistics for a city
  .eslintignore
  src/@types/index.d.ts
  src/components/CircularLoader/index.tsx
  src/components/CircularLoader/styles.ts
  src/components/HeaderTitle/styles.ts
  src/routes.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/CityStatistics/styles.ts
  src/screens/CityStatistics/yearsConstants.ts
  src/screens/HeatMap/index.tsx
  src/screens/Occurrences/index.tsx
  src/screens/Profile/styles.ts
  src/services/occurrencesSecretary.tsx
  yarn.lock
Labels: feature

#47 Create a context and a theme
  App.tsx
  src/@types/styled-components.d.ts
  src/components/CircularLoader/index.tsx
  src/components/HeaderTitle/index.tsx
  src/components/HeaderTitle/styles.ts
  src/components/LoggedInModal.tsx
  src/components/NormalForms.tsx
  src/components/StayAlert/styles.ts
  src/hooks/index.tsx
  src/hooks/user.tsx
  src/navigation/HomeTabBar.tsx
  src/routes.tsx
  src/screens/Cadastro/index.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/CityStatistics/styles.ts
  src/screens/HeatMap/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/searchOptions.ts
  src/screens/Home/styles.ts
  src/screens/Login/index.tsx
  src/screens/Occurrence/dropdownConstants.ts
  src/screens/Occurrence/index.tsx
  src/screens/Occurrence/styles.ts
  src/screens/OccurrenceDetails/styles.ts
  src/screens/Occurrences/index.tsx
  src/screens/Occurrences/styles.ts
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Report/index.tsx
  src/screens/Report/styles.ts
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
  src/services/occurrences.tsx
  src/styles/staySafeDarkTheme.ts
  src/styles/staySafeTheme.ts
Labels: enhancement

#54 Refactor heat map
  src/components/HeatMap/coordinates.ts
  src/components/HeatMap/index.tsx
  src/img/logo-thief-dark.svg
  src/navigation/HomeTabBar.tsx
  src/screens/CityStatistics/index.tsx
  src/screens/HeatMap/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/searchOptions.ts
  src/screens/Home/styles.ts
  src/services/coordinateSecretary.ts
  src/services/occurrencesSecretary.tsx
  src/styles/staySafeDarkMapStyle.ts
  src/styles/staySafeDarkTheme.ts
  src/styles/staySafeTheme.ts
Labels: feature

#56 Show user current position on map
  debug.log
  package.json
  src/screens/Home/index.tsx
  src/screens/Home/styles.ts
Labels: enhancement
