Repository fga-eps-mds/2020.1-stay-safe-front-end, pull requests merged in 2020-09, with the labels that each got.

#4 Creating Register Screen
  .gitignore
  App.tsx
  app.json
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  metro.config.js
  package-lock.json
  package.json
  src/components/NormalForms.js
  src/fonts/TruenoBd.otf
  src/fonts/TruenoRg.otf
  src/fonts/TruenoSBd.otf
  src/img/logo.svg
  src/routes.js
  src/screens/Cadastro/index.js
  src/utils/scalling.js
  tsconfig.json
Labels: feature

#6 Integrating register user with api
  .gitignore
  App.tsx
  app.json
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  metro.config.js
  package-lock.json
  package.json
  src/components/NormalForms.js
  src/fonts/TruenoBd.otf
  src/fonts/TruenoRg.otf
  src/fonts/TruenoSBd.otf
  src/img/logo.svg
  src/routes.js
  src/screens/Cadastro/index.js
  src/services/api.js
  src/services/users.js
  src/utils/scalling.js
  src/utils/validateUser.js
  tsconfig.json
Labels: enhancement, feature

#7 Creating Login Screen
  package.json
  src/components/NormalForms.js
  src/routes.js
  src/screens/Cadastro/index.js
  src/screens/Login/index.js
Labels: feature

#16 Create a screen for viewing, editing and deleting user profile
  package.json
  src/components/HeaderTitle/index.tsx
  src/components/HeaderTitle/styles.ts
  src/routes.js
  src/screens/Cadastro/index.js
  src/screens/Login/index.js
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Settings/styles.ts
  src/services/users.js
  src/utils/validateUpdateUser.ts
Labels: feature

#19 Add Tab Bar navigation and empty screens
  package-lock.json
  package.json
  src/navigation/HomeTabBar.js
  src/navigation/styles.js
  src/routes.js
  src/screens/Home/index.js
  src/screens/Report/index.js
  src/screens/Search/index.js
Labels: feature

#17 Create Occurrence Register Screen
  package-lock.json
  package.json
  src/components/HeaderTitle/index.tsx
  src/components/HeaderTitle/styles.ts
  src/screens/Occurrence/dropdownConstants.ts
  src/screens/Occurrence/index.tsx
  src/screens/Occurrence/styles.ts
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
  src/services/occurrences.js
  src/utils/validateOccurrence.js
Labels: feature

#18 Create User Logged In Modal Component
  package-lock.json
  package.json
  src/components/LoggedInModal.js
  src/components/StayAlert.js
  src/screens/Cadastro/index.js
  src/screens/Home/index.js
  src/screens/Login/index.js
Labels: feature

#20 Adding all screens to Bottom Tab Bar
  package-lock.json
  src/components/LoggedInModal.js
  src/navigation/HomeTabBar.js
  src/navigation/HomeTabBar.tsx
  src/routes.js
  src/screens/Home/index.js
  src/screens/Home/index.tsx
  src/screens/Profile/index.tsx
  src/screens/Report/index.js
  src/screens/Report/styles.js
  src/screens/Search/index.js
  src/screens/Search/index.tsx
  src/screens/Settings/buttonsObject.ts
  src/screens/Settings/index.tsx
  src/screens/Settings/styles.ts
Labels: enhancement, feature

#25 Adjust the background color of some pages
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/screens/Settings/index.tsx
Labels: bug
